export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import './globals.css';
import Navbar from './navbar';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  )

function ClientLayout({ children }: { children: React.ReactNode }) {
  if (typeof window !== 'undefined') {
    const path = window.location.pathname;
    const isAuthPage = path === '/login' || path === '/register';
    const token = localStorage.getItem('token');
    if (isAuthPage || !token) {
      return <>{children}</>;
    }
    return <><Navbar />{children}</>;
  }
  // SSR fallback
  return <>{children}</>;
}
}
